spring:
  datasource:
    url: jdbc:mysql://39.106.148.44:3306/xiermall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
   db-config:
     id-type: auto
server:
  port: 7000